import { ROUTES } from "@/constants/routes";

/**
 * 라우트 접근 레벨 정의
 *
 * - PUBLIC_ROUTES: 로그인 없이 접근 가능 (인증/회원가입 관련)
 * - PRIVATE_ROUTES: 로그인 필수 (메인 서비스 페이지)
 *
 * 새 페이지 추가 시 해당 접근 레벨에 맞게 여기에도 등록할 것
 */

/** 로그인 없이 접근 가능한 공개 라우트 */
export const PUBLIC_ROUTES = [
  ROUTES.ROOT,
  ROUTES.AUTH.LANDING,
  ROUTES.AUTH.SIGNIN,
  // 회원가입
  ROUTES.AUTH.SIGNUP.TERMS,
  ROUTES.AUTH.SIGNUP.CREDENTIALS,
  ROUTES.AUTH.SIGNUP.VERIFY,
  ROUTES.AUTH.SIGNUP.PROFILE,
  ROUTES.AUTH.SIGNUP.COMPLETE,
  // 계정 찾기
  ROUTES.AUTH.FIND_ACCOUNT,
  ROUTES.AUTH.FIND_RESULT,
  ROUTES.AUTH.FIND_RESET_PASSWORD,
  // 인증번호 확인
  ROUTES.AUTH.VERIFY.SIGNUP,
  ROUTES.AUTH.VERIFY.FIND_ID,
  ROUTES.AUTH.VERIFY.RESET_PASSWORD,
] as const;

/** 로그인이 필요한 인증 라우트 */
export const PRIVATE_ROUTES = [
  // 메인
  ROUTES.MAIN.HOME,
  ROUTES.MAIN.PROFILE,
  ROUTES.MAIN.PROFILE_EDIT,
  ROUTES.MAIN.SETTINGS,
  ROUTES.MAIN.CHAT,
  ROUTES.MAIN.NOTIFICATION,
  // 일정
  ROUTES.PLAN.LIST,
  ROUTES.PLAN.DATE,
  ROUTES.PLAN.LOCATION,
  ROUTES.PLAN.SETTING,
  ROUTES.PLAN.STYLE,
  ROUTES.PLAN.CREATE,
  ROUTES.PLAN.DETAIL,
  ROUTES.PLAN.SEARCH,
  // 사용자
  ROUTES.USER.DETAIL,
] as const;
