name: Deploy Frontend [main/release]

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup SSH key [main/release]
        run: |
          if [[ "${GITHUB_REF##*/}" == "release" ]]; then
            echo "${{ secrets.PROD_PRIVATE_KEY }}" > key.pem
          else
            echo "${{ secrets.TEST_PRIVATE_KEY }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Set Environment Variables [release]
        if: github.ref == 'refs/heads/release'
        run: |
          echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.PROD_USERNAME }}" >> $GITHUB_ENV
          echo "TARGET_DIR=/srv/barogagi/frontend/dist" >> $GITHUB_ENV

      - name: Set Environment Variables [main]
        if: github.ref == 'refs/heads/main'
        run: |
          echo "HOST=${{ secrets.TEST_HOST }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.TEST_USERNAME }}" >> $GITHUB_ENV
          echo "TARGET_DIR=/srv/barogagi-test/frontend/dist" >> $GITHUB_ENV

      - name: Create .env file from Secrets [release]
        if: github.ref == 'refs/heads/release'
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.PROD_VITE_API_BASE_URL }}" >> .env
          echo "VITE_API_KEY=${{ secrets.PROD_VITE_API_KEY }}" >> .env

      - name: Create .env file from Secrets [main]
        if: github.ref == 'refs/heads/main'
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.TEST_VITE_API_BASE_URL }}" >> .env
          echo "VITE_API_KEY=${{ secrets.TEST_VITE_API_KEY }}" >> .env

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          set -e
          ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo mkdir -p $TARGET_DIR && sudo chown $USERNAME:$USERNAME $TARGET_DIR && rm -rf $TARGET_DIR/*"
          scp -i key.pem -o StrictHostKeyChecking=no -r ./dist/. $USERNAME@$HOST:$TARGET_DIR/